In [1]:
import numpy as np
import pandas as pd


import plotly.offline as pyo
pyo.init_notebook_mode(connected=True)
pd.options.plotting.backend = 'plotly'

In [3]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [13]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 39.875, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 39.875, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X

array([[0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 1.0, 0.0, 39.875, 54000.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 1.0, 39.875, 52000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [22]:
X_train, y_train, X_test, y_test

(array([[1.0, 0.0, 0.0, 1.0, 39.875, 52000.0],
        [1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
        [0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
        [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
        [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
        [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
        [1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
        [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object),
 array([0, 1, 0, 0, 1, 1, 0, 1]),
 array([[1.0, 0.0, 1.0, 0.0, 39.875, 54000.0],
        [0.0, 1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object),
 array([0, 1]))

In [23]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train[:, 4:] = scaler.fit_transform(X_train[:, 4:])
X_test[:, 4:] = scaler.transform(X_test[:, 4:])

In [24]:
X_train, X_test

(array([[1.0, 0.0, 0.0, 1.0, -0.05231070414657415, -1.0781259408412425],
        [1.0, 0.0, 1.0, 0.0, -0.03411567661733096, -0.07013167641635372],
        [0.0, 1.0, 0.0, 0.0, 0.5481252043184508, 0.633562432710455],
        [1.0, 0.0, 0.0, 1.0, -0.3252361170852219, -0.30786617274297867],
        [1.0, 0.0, 0.0, 1.0, -1.9263985396586218, -1.420463615551582],
        [0.0, 1.0, 0.0, 0.0, 1.1303660852542325, 1.232653363453549],
        [1.0, 0.0, 1.0, 0.0, 1.4214865257221234, 1.5749910381638885],
        [0.0, 1.0, 0.0, 0.0, -0.7619167777870582, -0.5646194287757332]],
       dtype=object),
 array([[1.0, 0.0, 1.0, 0.0, -0.05231070414657415, -0.9069571034860727],
        [0.0, 1.0, 0.0, 0.0, -0.4707963373191673, 0.2056403393225306]],
       dtype=object))